steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/sales-dashboard-461208/my-repo/sales-dashboard'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/sales-dashboard-461208/my-repo/sales-dashboard'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'us-central1-docker.pkg.dev/sales-dashboard-461208/my-repo/sales-dashboard'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--port'
  - '8080'
  - '--timeout'
  - '6000s'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'sales-dashboard-461208@appspot.gserviceaccount.com'
  - '--set-env-vars'
  - 'GOOGLE_CLOUD_PROJECT=sales-dashboard-461208,GCS_BUCKET_NAME=data-sales-dashboard,GCS_BLOB_NAME=Data-Set (1).csv'