version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dashboard-backend
    ports:
      - "8000:8000"
    environment:
      - DRUID_BROKER_HOST=druid-broker
      - DRUID_BROKER_PORT=8888
      - DRUID_DATASOURCE=sales_data
      - PYTHONPATH=/app
    depends_on:
      - druid-broker
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dashboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Druid Coordinator
  druid-coordinator:
    image: apache/druid:0.23.0
    container_name: druid-coordinator
    ports:
      - "8081:8081"
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - druid_extensions_directory=/opt/druid/extensions
      - druid_extensions_hadoopDependenciesDir=/opt/hadoop-dependencies
      - druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]
      - druid_zk_service_host=zookeeper
      - druid_metadata_storage_host=postgres
      - druid_metadata_storage_type=postgresql
      - druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
      - druid_metadata_storage_connector_user=druid
      - druid_metadata_storage_connector_password=druid
      - druid_coordinator_balancer_strategy=cachingCost
      - druid_indexer_runner_javaOptsArray=["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]
      - druid_indexer_fork_property_druid_processing_buffer_sizeBytes=268435456
    volumes:
      - druid_coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    command: coordinator
    restart: unless-stopped

  # Druid Broker
  druid-broker:
    image: apache/druid:0.23.0
    container_name: druid-broker
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - druid_extensions_directory=/opt/druid/extensions
      - druid_extensions_hadoopDependenciesDir=/opt/hadoop-dependencies
      - druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]
      - druid_zk_service_host=zookeeper
      - druid_metadata_storage_host=postgres
      - druid_metadata_storage_type=postgresql
      - druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
      - druid_metadata_storage_connector_user=druid
      - druid_metadata_storage_connector_password=druid
      - druid_broker_http_numConnections=5
      - druid_server_http_numThreads=40
      - druid_processing_buffer_sizeBytes=268435456
      - druid_processing_numMergeBuffers=6
      - druid_processing_numThreads=2
      - druid_sql_enable=true
    volumes:
      - druid_broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    command: broker
    restart: unless-stopped

  # Druid Historical
  druid-historical:
    image: apache/druid:0.23.0
    container_name: druid-historical
    ports:
      - "8083:8083"
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - druid_extensions_directory=/opt/druid/extensions
      - druid_extensions_hadoopDependenciesDir=/opt/hadoop-dependencies
      - druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]
      - druid_zk_service_host=zookeeper
      - druid_metadata_storage_host=postgres
      - druid_metadata_storage_type=postgresql
      - druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
      - druid_metadata_storage_connector_user=druid
      - druid_metadata_storage_connector_password=druid
      - druid_server_http_numThreads=40
      - druid_processing_buffer_sizeBytes=268435456
      - druid_processing_numMergeBuffers=6
      - druid_processing_numThreads=2
      - druid_segmentCache_locations=[{"path":"/opt/druid/var/druid/segment-cache","maxSize":10000000000}]
      - druid_server_maxSize=10000000000
    volumes:
      - druid_historical_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    command: historical
    restart: unless-stopped

  # Druid MiddleManager
  druid-middlemanager:
    image: apache/druid:0.23.0
    container_name: druid-middlemanager
    ports:
      - "8091:8091"
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - druid_extensions_directory=/opt/druid/extensions
      - druid_extensions_hadoopDependenciesDir=/opt/hadoop-dependencies
      - druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]
      - druid_zk_service_host=zookeeper
      - druid_metadata_storage_host=postgres
      - druid_metadata_storage_type=postgresql
      - druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
      - druid_metadata_storage_connector_user=druid
      - druid_metadata_storage_connector_password=druid
      - druid_worker_capacity=4
      - druid_indexer_runner_javaOptsArray=["-server", "-Xmx1g", "-Xms1g", "-XX:MaxDirectMemorySize=3g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]
      - druid_indexer_task_baseTaskDir=/opt/druid/var/druid/task
    volumes:
      - druid_middlemanager_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    command: middleManager
    restart: unless-stopped

  # Druid Router
  druid-router:
    image: apache/druid:0.23.0
    container_name: druid-router
    ports:
      - "8889:8888"
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - druid_extensions_directory=/opt/druid/extensions
      - druid_extensions_hadoopDependenciesDir=/opt/hadoop-dependencies
      - druid_extensions_loadList=["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage"]
      - druid_zk_service_host=zookeeper
      - druid_metadata_storage_host=postgres
      - druid_metadata_storage_type=postgresql
      - druid_metadata_storage_connector_connectURI=jdbc:postgresql://postgres:5432/druid
      - druid_metadata_storage_connector_user=druid
      - druid_metadata_storage_connector_password=druid
      - druid_router_http_numConnections=50
      - druid_server_http_numThreads=40
      - druid_router_http_numMaxThreads=100
      - druid_router_http_compression=true
      - druid_router_tierToBrokerMap={"_default_tier":"druid-broker:8888"}
      - druid_router_defaultBrokerServiceName=druid/broker
      - druid_router_coordinatorServiceName=druid/coordinator
      - druid_router_managementProxy_enabled=true
    volumes:
      - druid_router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - druid-broker
      - druid-coordinator
    command: router
    restart: unless-stopped

  # Zookeeper for Druid
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    restart: unless-stopped

  # PostgreSQL for Druid metadata
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=druid
      - POSTGRES_USER=druid
      - POSTGRES_PASSWORD=druid
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  druid_coordinator_var:
  druid_broker_var:
  druid_historical_var:
  druid_middlemanager_var:
  druid_router_var:
  zookeeper_data:
  zookeeper_datalog:
  postgres_data:

networks:
  default:
    name: dashboard-network
