version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dashboard-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DRUID_BROKER_HOST=host.docker.internal 
      - DRUID_BROKER_PORT=8888
      - DRUID_DATASOURCE=sales_analytics
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: dashboard-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_PORT=5173

networks:
  default:
    name: dashboard-dev-network
